<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSS9eBKl\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSS9eBKl/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSS9eBKl.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSS9eBKl\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerSS9eBKl\srcDevDebugProjectContainer([
    'container.build_hash' => 'SS9eBKl',
    'container.build_id' => '86cfa705',
    'container.build_time' => 1572800575,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSS9eBKl');
