<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Xn1ma0o' shared service.

return $this->privates['.service_locator.Xn1ma0o'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['likeRepo' => function (): \App\Repository\PostLikeRepository {
    return ($this->privates['App\\Repository\\PostLikeRepository'] ?? $this->load('getPostLikeRepositoryService.php'));
}, 'manager' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}, 'post' => function (): \App\Entity\Post {
    return ($this->privates['.errored..service_locator.Xn1ma0o.App\\Entity\\Post'] ?? $this->load('getPostService.php'));
}]);
